### ISSUE TITLE
Separate script and library

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/node-api#7]
During discussion, similar to how it's done in the [diagnostic](https://github.com/ga-wdi-boston/node-api-diagnostic) 
- @gaand

**Comment by jrhorn424** [comment]
Does this mean separate files into a `data` directory? Or something about `lib` and `scripts`? or `bin`? 🤔

**Comment by gaand** [comment]
I think add a `bin` for the things that run from the command line, `lib` contains code required and invoked by those.  

Better separation of concerns, etc.

@jrhorn424 Please let me know if you need more clarification.
